
-- Envía a la consola ingresos de especialidades de acuerdo a un 
-- rango determinado de fechas. 
 CREATE OR REPLACE PROCEDURE INGRESOS_RANGO (FECHA01 IN DATE , FECHA02 IN DATE) AS
NUM INGESPECIALIDADFECHA.INGRESOS%TYPE;
NOM INGESPECIALIDADFECHA.NOMBRE%TYPE;
T INGESPECIALIDADFECHA.FECHA%TYPE;
FE CONSULTA.FECHA%TYPE;
  cursor C1 is
   SELECT DISTINCT I.NOMBRE , I.INGRESOS, I.FECHA
   FROM INGESPECIALIDADFECHA I
      WHERE I.FECHA BETWEEN FECHA01 AND FECHA02;
   BEGIN
  open C1;
   LOOP
   fetch C1 into NOM , NUM, T;
    EXIT WHEN C1%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(NOM || ' ---- ' || NUM || '----' || T);
    END LOOP;
   close C1;
END;
/

