--DISPARADOR MENSAJE_DE_AGREGADO
--Imprime un mensaje en la consola ya que se ha agregado una consulta.
CREATE OR REPLACE 
TRIGGER MENSAJE_DE_AGREGADO
AFTER INSERT ON CONSULTA
REFERENCING OLD AS OLD NEW AS NEW
DECLARE
BEGIN 
DBMS_OUTPUT.PUT_LINE('SE HA AGREGADO UNA NUEVA CONSULTA'); 
END;