--Script para crear tabla médico
CREATE TABLE MEDICO (

IDMEDICO NUMBER NOT NULL,
IDESPECIALIDAD NUMBER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
PATERNO VARCHAR2(50) NOT NULL,
MATERNO VARCHAR2(50) NOT NULL,
PRIMARY KEY (IDMEDICO),
FOREIGN KEY (IDESPECIALIDAD) REFERENCES ESPECIALIDAD

);

