CREATE OR REPLACE VIEW ESPECIALIDAD_HORAS
AS
SELECT E.NOMBRE , SUM(I.DURACION) HORAS FROM INFORMACION_COMPLETA I 
INNER JOIN ESPECIALIDAD E
ON I.IDESPECIALIDAD=E.IDESPECIALIDAD
GROUP BY E.NOMBRE;