CREATE OR REPLACE VIEW MEDICO_Y_CONSULTAS 
AS
SELECT M.IDMEDICO
,M.IDESPECIALIDAD
,M.NOMBRE
,M.PATERNO
,M.MATERNO
,C.IDCONSULTA
,C.FECHA
,C.DURACION
,C.PRECIO
FROM MEDICO M
INNER JOIN CONSULTA C
ON M.IDMEDICO = C.IDMEDICO;
